site_name: pimdb
site_description: Build a database from IMDb datasets
site_author: Thomas Aglassinger
repo_url: https://github.com/roskakori/pimdb
repo_name: roskakori/pimdb
edit_uri: edit/master/docs/
site_url: https://pimdb.readthedocs.io/
copyright: Copyright &copy; 2020-2025 Thomas Aglassinger

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

nav:
  - Home: index.md
  - License: license.md
  - Installation: installation.md
  - Usage: usage.md
  - Data Model: datamodel.md
  - Contributing: contributing.md
  - Changes: changes.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true

plugins:
  - search
